Deploy to prod
ensdomains/ens-app pull request #1181
Opened 2021-06-18 05:27 UTC by LeonmanRolls

## Issue number

## Description

## List of features added/changed

-
-
-

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My code implements all the required features.

2021-06-18 10:06 UTC, makoto commented
We use `yarn.lock` so `package-lock.json` shouldn't be committed.

2021-06-18 10:06 UTC, makoto requested changes
Please do not commit package-lock.json but use yarn to install packages

2021-06-18 10:07 UTC, makoto commented on src/index.js
> +// import 'core-js/es/object'
Please remove it if you don't need it any more

2021-06-21 08:57 UTC, jefflau approved these changes

2021-06-21 08:59 UTC, merged