feat: v3 banner
ensdomains/ens-app pull request #1604
Opened 2023-02-16 02:17 UTC by TateB

2023-02-19 20:28 UTC, LeonmanRolls requested changes
<img width="635" alt="image" src="https://user-images.githubusercontent.com/1221151/219973489-2404f3d3-c69f-4a7d-8c7d-ae3a08c39939.png">
Think the arrow looks a bit weird, maybe use a horizontal one? Or position it differently

2023-02-19 23:26 UTC, TateB commented
pushed the banner arrow up a bit

2023-02-22 12:48 UTC, LeonmanRolls approved these changes

2023-04-17 01:55 UTC, LeonmanRolls approved these changes

2023-04-18 02:50 UTC, merged