secure ipfs gateway
ensdomains/ens-app pull request #538
Opened 2019-11-27 16:27 UTC by pldespaigne

Hello guys 👋 @makoto @Arachnid @jefflau 

I have updated the code resolve ipfs hash trough a secure gateway.
This is a huge security improvement.

This PR has a dependency on this other PR 👇 

Everything is detailed on the other [PR](https://github.com/ensdomains/ui/pull/46)

As always thanks a lot for your time and your work!

PS : you can read more about secure ipfs in this [MetaMask PR](https://github.com/MetaMask/metamask-extension/pull/7362)

2020-08-20 22:00 UTC, lidel commented on src/components/Links/ContentHashLink.js
>    if (protocolType === 'ipfs') {
`https://dweb.link/ipfs/${decoded}` will also work (will redirect to correct subdomain + convert CID to DNS-compatible encoding, if needed)

2020-08-20 22:01 UTC, lidel commented on src/components/Links/ContentHashLink.js
> +    externalLink = `https://${decoded}.ipfs.dweb.link` // using ipfs's secured origin gateway
`https://dweb.link/ipfs/${decoded}` will also work (will redirect to correct subdomain + convert CID to DNS-compatible encoding, if needed)

2020-09-15 14:01 UTC, lidel requested changes
@pldespaigne see comment inline

2020-09-15 14:01 UTC, lidel commented on src/components/Links/ContentHashLink.js
> +    externalLink = `https://${decoded}.ipfs.dweb.link` // using ipfs's secured origin gateway
```suggestion
    externalLink = `https://dweb.link/ipfs/${decoded}` // using ipfs's secured origin gateway
```

We recommend keeping the path-based router for improved compatibility.
go-ipfs 0.5+ will redirect to correct subdomain, and go-ipfs 0.7+ will convert CID to DNS-compatible encoding, if needed

2020-10-06 18:43 UTC, makoto commented
Duplicate to https://github.com/ensdomains/ens-app/pull/936

2020-10-06 18:43 UTC, closed without merging